### ISSUE TITLE
[doc] 6.5.3.5  Deploy NFS Ganesha

### ISSUE THREAD

**Issue by lezare** [SUSE/doc-ses#465]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
6.5.3.5  Deploy NFS Ganesha:

https://susedoc.github.io/doc-ses/master/single-html/ses-deployment/#deploy-cephadm-day2-service-nfs

### Summary
The documentation is not clear here I believe, "pre-defined" for example can be changed to "existing". It needs to be made clear the configured "pool:" in the NFS yml config should already exist BEFORE running the deployment.

### Notes
If the pool does not exist, cephadm will show it is pushing out the config, no errors, but nothing will happen. Only way to then see that it failed is to look at the last cephadm logged entries which will show the check for pool existence failing:

`2020-08-14T08:06:42.169055+0000 mgr.vm-el-ses7-n2.ugngqb (mgr.14183) 31062 : cephadm [INF] Checking pool "ganesha_config" exists for service nfs.el_nfs
2020-08-14T08:06:42.173651+0000 mgr.vm-el-ses7-n2.ugngqb (mgr.14183) 31063 : cephadm [ERR] Failed to apply nfs.el_nfs spec NFSServiceSpec({'placement': PlacementSpec(hosts=[HostPlacementSpec(hostname='vm-el-ses7-n6', network='', name='')]), 'service_type': 'nfs', 'service_id': 'el_nfs', 'unmanaged': False, 'preview_only': False, 'pool': 'ganesha_config', 'namespace': 'nfs'}): Cannot find pool "ganesha_config" for service nfs.el_nfs
Traceback (most recent call last):
  File "/usr/share/ceph/mgr/cephadm/module.py", line 2071, in _apply_all_services
    if self._apply_service(spec):
  File "/usr/share/ceph/mgr/cephadm/module.py", line 2029, in _apply_service
    config_func(spec)
  File "/usr/share/ceph/mgr/cephadm/services/nfs.py", line 73, in config
    self.mgr._check_pool_exists(spec.pool, spec.service_name())
  File "/usr/share/ceph/mgr/cephadm/module.py", line 2083, in _check_pool_exists
    raise OrchestratorError(f'Cannot find pool "{pool}" for '
orchestrator._interface.OrchestratorError: Cannot find pool "ganesha_config" for service nfs.el_nfs
`

**Comment by asettle** [comment]
Will be tracking this as part of a larger issue where we work on the NFS Ganesha docs. This issue is linked from 477

New NFS Ganesha issue: https://github.com/SUSE/doc-ses/issues/477
