### ISSUE TITLE
[doc] 5.4.3.3  Deploy Metadata Servers

### ISSUE THREAD

**Issue by ryg-** [SUSE/doc-ses#670]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
5.4.3.3  Deploy Metadata Servers:

https://susedoc.github.io/doc-ses/master/single-html/ses-deployment/#deploy-cephadm-day2-service-mds

### Summary
PLACEMENT_STRING parameter is not explained

### Expected Results
Optional parameter could be removed or should be described

**Comment by ryg-** [comment]
Error message for simple string

------------
ceph fs volume create CEPHFS_NAME my_ceph_placement
Error EINVAL: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ceph/deployment/service_spec.py", line 34, in assert_valid_host
    assert p.match(part), 'name component must include only a-z, 0-9, and -'
AssertionError: name component must include only a-z, 0-9, and -

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/ceph/mgr/mgr_module.py", line 1188, in _handle_command
    return self.handle_command(inbuf, cmd)
  File "/usr/share/ceph/mgr/volumes/module.py", line 367, in handle_command
    return handler(inbuf, cmd)
  File "/usr/share/ceph/mgr/volumes/module.py", line 372, in _cmd_fs_volume_create
    return self.vc.create_fs_volume(vol_id, placement)
  File "/usr/share/ceph/mgr/volumes/fs/volume.py", line 87, in create_fs_volume
    return create_volume(self.mgr, volname, placement)
  File "/usr/share/ceph/mgr/volumes/fs/operations/volume.py", line 70, in create_volume
    return create_mds(mgr, volname, placement)
  File "/usr/share/ceph/mgr/volumes/fs/fs_util.py", line 41, in create_mds
    placement=PlacementSpec.from_string(placement))
  File "/usr/lib/python3.6/site-packages/ceph/deployment/service_spec.py", line 366, in from_string
    host_pattern=host_patterns[0] if host_patterns else None)
  File "/usr/lib/python3.6/site-packages/ceph/deployment/service_spec.py", line 169, in __init__
    self.validate()
  File "/usr/lib/python3.6/site-packages/ceph/deployment/service_spec.py", line 276, in validate
    h.validate()
  File "/usr/lib/python3.6/site-packages/ceph/deployment/service_spec.py", line 143, in validate
    assert_valid_host(self.hostname)
  File "/usr/lib/python3.6/site-packages/ceph/deployment/service_spec.py", line 36, in assert_valid_host
    raise ServiceSpecValidationError(e)
ceph.deployment.service_spec.ServiceSpecValidationError: name component must include only a-z, 0-9, and -
